class TjaxController < ApplicationController
  around_action :deal_with_environment, only: [:convert]
  def convert
    respond_to do |f|
      f.png do
        latexpng(params['str'], inline: 1)
      end
    end
  end

  private

  def latexpng(string, options = {})
    str = render_to_string(
      template: 'tjax/math',
      formats: [:tex],
      locals: { string: string })
    File.open('tmp.tex', 'w:UTF-8') do |f|
      f.write(str)
    end
    `pdflatex -halt-on-error tmp.tex`
    `convert -trim -density 150 tmp.pdf tmp.png`
    path = File.expand_path('tmp.png')
    begin
      send_data(
        Base64.encode64(File.read(path)),
        type: 'image/png',
        disposition: 'inline',
        encoding: 'utf8')
    rescue Errno::ENOENT
      raise "No output generated by XeTex, see log: \n #{File.read('tmp.log')}"
    end
  end

  def deal_with_environment(&_b)
    dir = "tmp/tjax/#{session.hash.abs}"
    `mkdir -p #{dir}`
    fork do
      sleep 5
      `rm -rf #{dir}`
    end
    Dir.chdir(dir) do
      yield
    end
  end
end
